// =============================================================================
//                        !!! DO NOT EDIT THIS FILE !!!
// =============================================================================

#pragma once
#include <string>
#include <vector>

/// this is the function you need to implement in deadlock.cpp
/// do not edit this signature !!!
void detect_deadlock(
    const std::vector<std::string>& lines, int& line_number,
    std::vector<std::string>& deadlocked_processes);
