// =============================================================================
//                        !!! DO NOT EDIT THIS FILE !!!
// =============================================================================

#pragma once
#include <string>
#include <vector>

/// this is the function you need to implement in deadlock_detector.cpp
/// do not edit this signature !!!
void detect_deadlock(
    const std::vector<std::string> & edges, int & edge_index, std::vector<std::string> & cycle);